config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, inclusion: { in:  (1..5) }, presence: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @blank_cocktail = Cocktail.new
  end

  def show 
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail.id)
  end

  def new 
    @cocktail = Cocktail.new
  end

  def create 
    @cocktail = Cocktail.new(strong_params)
    if @cocktail.valid?
      ingredients = [ params[:ingredient1], params[:ingredient2], params[:ingredient3] ]
      amounts = [ params[:ingredient1_amount], params[:ingredient2_amount], params[:ingredient3_amount] ]
      pairings = ingredients.zip(amounts)

      doses = []

      pairings.each do |ingredient_name, amount|
        doses << Dose.new(ingredient: Ingredient.where(name:ingredient_name).first, cocktail: @cocktail, description: amount)
      end

      if doses.all? { |dose| dose.valid? }
        doses.each { |dose| dose.save }
        redirect_to cocktails_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def strong_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/index.html.erb
<header class="d-flex justify-content-between align-items-center">
  <h1 class="mb-4"><i class="fas fa-feather-alt"></i> <strong>Ye Olde Potion Shop</strong></h1>
  <%= link_to "Blend Your Own Potion", new_cocktail_path, class: "btn btn-danger"%>
</header>
<div class="d-flex justify-content-center">
  <div class="cards-grid my-5">
    <% @cocktails.each do |cocktail| %>
      <div class="card">
        <%= cl_image_tag cocktail.photo.key, class: "card-img-top", style: "height: 200px;"%>
        <div class="card-body p-3 d-flex flex-column justify-content-between">
          <h2 class="card-title"><strong><%= cocktail.name %></strong></h2>
          <p><%= "⭐" * cocktail.rating %></p>
          <p class="card-text" style="color:black;"><%= cocktail.description %></p>
          <%= link_to "Discover More", cocktail_path(cocktail), class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<header class="d-flex justify-content-between align-items-center">
  <h2>Blend Your Own Potion</h2>
  <%= link_to "Back to shop", cocktails_path, class: "btn btn-danger" %>
</header>
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "e.g. Long Life Potion"%>
  <%= f.input :description, placeholder: "What does this potion do?" %>
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <label for="ingredient1">Ingredient 1 <abbr title="required">*</abbr></label>
        <select class="form-control" id="ingredient1" name="ingredient1" required>
          <% Ingredient.all.each do |ingredient| %>
            <option><%= ingredient.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label for="ingredient1-amount">Quantity <abbr title="required">*</abbr></label>
        <input class="form-control" type="text" name="ingredient1_amount" id="ingredient1-amount" placeholder="e.g. 250g, 1 vial, etc." required>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <label for="ingredient2">Ingredient 2 <abbr title="required">*</abbr></label>
        <select class="form-control" id="ingredient2" name="ingredient2" required>
          <% Ingredient.all.each do |ingredient| %>
            <option><%= ingredient.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label for="ingredient2-amount">Quantity <abbr title="required">*</abbr></label>
        <input class="form-control" type="text" name="ingredient2_amount" id="ingredient2-amount" placeholder="e.g. 250g, 1 vial, etc." required>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <label for="ingredient3">Ingredient 3 <abbr title="required">*</abbr></label>
        <select class="form-control" id="ingredient3" name="ingredient3" required>
          <% Ingredient.all.each do |ingredient| %>
            <option><%= ingredient.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <label for="ingredient3-amount">Quantity <abbr title="required">*</abbr></label>
        <input class="form-control" type="text" name="ingredient3_amount" id="ingredient3-amount" placeholder="e.g. 250g, 1 vial, etc." required>
      </div>
    </div>
  </div>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Mix Potion", class:"btn btn-danger" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name  %></h1>

<div class="cocktail-show-card">
  <div class="container px-0">
    <div class="row h-100">
      <div class="col-xs-12 col-md-4">
        <%= content_tag :div, "", class: "potion-img", style: "background-image: url(#{cl_image_path @cocktail.photo.key});" %>
      </div>
      <div class="col-xs-12 col-md-8 cocktail-description">
        <div class="p-4">
          <h2><%= @cocktail.name %></h2>
          <p><%= "⭐" * @cocktail.rating %></p>
          <p><%= @cocktail.description %></p>
          <div class="btn btn-danger p-3">Add to Cart</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="ingredients-container p-5">
  <h2>Ingredients</h2>
  <ul>
    <% @doses.each do |dose| %>
      <li><%= dose.description %> <%= dose.ingredient.name %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ye Olde Potion Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="container py-5">
      <%= yield %>
    </div>
    <%= image_tag "cocktails/smoke.png", id:"smoke" %>
  </body>
</html>